### ISSUE TITLE
設計 TODO

### ISSUE THREAD

**Issue by wutingy** [goodjoblife/GoodJobShare#25]
### 現階段
- [x] 各頁面的 og image
- [x] 小教室出圖

### 面試工作經驗
- [ ] 列表頁 load more button 設計
- [x] 工作經驗表單（4/8 前會完成）
- [x] 工作經驗單篇（4/8 前會完成）
- [x] 面試經驗單篇左側欄位有缺少，要補上
- [x] icon 出圖
- [x] 下集小教室文案、排程

### 工時薪資
- [ ] 設計刪除資料的檢舉按鈕在 table 上

### 其他
- [x] 週年圖
- [x] 回信（新設計）

### 名片設計
- [x] 款一
- [x] 款二
- [x] 完稿
https://paper.dropbox.com/doc/DP2oUnT8F4GkWXuXTYOjw

### TNL 活動設計
https://paper.dropbox.com/doc/kpAzQuHaZNYUi8u2MJzxX 
- [x] 各種 Banners
- [x] GoodJob 形象貼紙
- [x] GoodJob 形象 易拉展 x1
- [x] Zine (內容是某堂的小教室)（待確認）
- [x] 工作人員名牌
- [x] A3 彩印 banner
