### ISSUE TITLE
全站 SEO 優化

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#637]
### Task 1 
- [ ] title, description, keywords 全面重新檢查
  - [ ] 使用 google trend 抓準常被搜尋的字詞
  - [ ] 觀察其他類似網站的 description 怎麼寫的

### Task 2
- [ ] 產生 structural data ，放到 html 裡面
 
送 structural data 給 google，可以讓使用者在搜尋時看到像這樣的區塊，進而增加點擊率

1. `Article` ，可以用在面試經驗、工作心得
<img width="402" alt="螢幕快照 2019-03-27 下午11 58 23" src="https://user-images.githubusercontent.com/3805975/55091776-68aa3580-50ec-11e9-9026-6df13599ad6c.png">

2. `Employer Aggregate Rating` 對公司的評價，可以用在面試經驗、工作心得
<img width="413" alt="螢幕快照 2019-03-27 下午11 58 53" src="https://user-images.githubusercontent.com/3805975/55091777-68aa3580-50ec-11e9-9286-53a929a71d81.png">

3. `Occupation` 可以用在薪資工時資料
<img width="412" alt="螢幕快照 2019-03-27 下午11 59 08" src="https://user-images.githubusercontent.com/3805975/55091778-68aa3580-50ec-11e9-9ed6-98b8fae7d663.png">

4. `Review snippet` 可以用在面試經驗、工作心得
<img width="416" alt="螢幕快照 2019-03-27 下午11 59 21" src="https://user-images.githubusercontent.com/3805975/55091780-6942cc00-50ec-11e9-88d3-5c8073bb47fd.png">

reference doc:
https://developers.google.com/search/docs/guides/search-gallery
