### ISSUE TITLE
新版表單 component 

### ISSUE THREAD

**Issue by barry800414** [goodjoblife/GoodJobShare#846]
### 簡介

因應日後表單題目會比較多變，甚至可能不是固定的。希望製作出一個可重複使用的 react component ，把題目以 props 傳入 ，就能產生一個可以填寫的表單，並有好的填寫體驗。

### Wireframe 示意圖
[axure wireframe](https://o2geqq.axshare.com/#id=41fl3m&p=%E8%A1%A8%E5%96%AE%E6%A1%86%E6%9E%B6&g=1
)
 
### UI design
#845   由 @wutingy  負責，預計 2/29 完成

### Component 結構
我直接寫了一個 component 結構的草稿，說明了有哪些可能的 props，然後推到 [form-builder](https://github.com/goodjoblife/GoodJobShare/tree/form-builder) branch 上了。未來開發時可能需要再小調整。

-> https://github.com/goodjoblife/GoodJobShare/blob/form-builder/src/components/common/FormBuilder/index.js

搶先看
```js
/*
  type = input            短文字題
       = textarea         長文字題
       = radio            單選題
       = checkbox         複選題
       = file             檔案上傳
       = rating           評分題（1-5分）
       = customized       複合型題，render function 由外部傳入
*/
const QuestionShape = shape({
  // 問題
  title: string.isRequired,
  // 問題描述
  description: string,
  // 問題種類
  type: oneOf([
    'input',
    'textarea',
    'radio',
    'checkbox',
    'rating',
    'file',
    'customized',
  ]).isRequired,
  // 該題的值的 key
  key: string.isRequired,
  // 此題是否必填
  required: bool.isRequired,
  // 驗證內容的函數
  validator: func,
  // 如果 type=customized，代表此題是從外部傳入 render function。
  // 能不用則不用。
  renderCustomizedQuestion: func,
});

const FormBuilder = () => {};

FormBuilder.propTypes = {
  // 表單是否開啟，等於 false 時表單關閉。
  open: bool.isRequired,
  // 問卷標題
  title: string.isRequired,
  // 問卷描述
  description: oneOfType([string, element]),
  // 上傳按鈕的文字
  submitButtonText: oneOfType([string, element]).isRequired,
  // 上傳按鈕是否可按
  submitButtonEnabled: bool.isRequired,
  // 問題列表
  questions: arrayOf(QuestionShape),
  // 排版方式，目前只有一種，就是 typeform
  layout: string.isRequired,
  // 當使用者填寫內容，此函數會被觸發，且 emit 一個 object，包含被修改欄位的 key & value
  onChange: func.isRequired,
  // 當使用者按下送出鈕，且通過所有 question validator 驗證，此函數會被觸發
  onSubmit: func.isRequired,
  // 當使用者按下送出鈕，但有 question validator 驗證未過，此函數會被觸發
  onValidateFail: func,
  // 點擊下一步可額外觸發的函數 (可用於數據追蹤)
  onNext: func,
  // 點擊上一步考額外觸發的函數 (可用於數據追蹤)
  onPrev: func,
  // 點擊使用者條款 checkbox
  onClickAgreement: func,
  // 點擊關閉表單按鈕觸發的函數
  onClickCloseBtn: func.isRequired,
  // 真正要關閉表單前觸發的函數（可用於將資料存到 local storage）
  onClose: func,

  // 訊息 Modal 的內容
  msgModalContent: oneOfType([string, element]),
  // 訊息 Modal 是否開啟
  openMsgModal: bool,
  // 使用者點擊 Modal 的關閉按鈕觸發的函數
  onCloseMsgModal: func,
  // 使用者點擊 Modal 的確認按鈕觸發的函數
  onConfirmMsgModal: func,
};

FormBuilder.defaultProps = {
  oepn: true,
  layout: 'typeform',
  openMsgModal: false,
};

export default FormBuilder;
```

## Tickets
我把這個 component 要做的事情稍微切開，不一定要按照這個切法去做

#### Stage 1. 基本 render
- [x] render form title & description
- [x] render `type = input` 短文字題
- [x] render `type = textarea` 長文字題，字數變多時，會明確計算字數
- [x] render `type=radio` 單選題，選項過多時，可以往下捲
- [x] render `type=checkbox` 複選題，選項過多時，可以往下捲
- [x] render `type=file`  檔案上傳題
- [x] render `type=rating`  評分題（1-5分）
- [x] render `type=customized`  複合型題，render function 由外部傳入
- [x] render submit button
- [x] render 進度（總共幾題、現在在第幾題）
- [x] render footer 

#### Stage 2. 基礎互動＆表單事件觸發
- [x] 點擊上一步、下一步可正常跳題
- [x] ~~點擊右上角 x 可觸發 onClickCloseBtn~~
- [x] 表單真正被關閉時，觸發 onClose 
- [x] 填寫表單題目可觸發 onChange function
- [x] 點擊送出按鈕時，觸發 onSubmit function
- [x] 當 openMsgModal = true 時，render msgModal 
- [x] 當點擊 message modal 的關閉按鈕時，觸發 onCloseMsgModal
- [x] 當點擊 message modal 的確認按鈕時，觸發 onConfirmMsgModal
- [x] ~~點擊我同意使用者挑款，觸發 `onClickAgreement`~~

#### Stage 3. 表單驗證
- [ ] 填寫單一題目時，觸發該題 question.validator ，檢查內容是否符合格式。若不符合，則跳出警告訊息（UI 待 @wutingy  確認）。該檢查雖然每一次 onChange 發生時觸發，但會 debounce 1 秒。
- [ ] 點擊送出按鈕時，觸發所有 question.validator，若有任一題未通過，則 scroll 到該題，並跳出警告訊息
- [ ] 點擊送出按鈕時，觸發所有 question.validator，若全數通過，才觸發 onSubmit function

#### Stage 4. 體驗優化
- [x] `type = input` 短文字題 內容輸入完按下 enter 時，自動跳下一題
- [x] `type=radio` 單選題，選了一個選項後，自動跳下一題
- [x] `type=rating`  評分題（1-5分），選了評分後，自動跳下一題
- [x] 跳上/下一題時的 animation

**Comment by mark86092** [comment]
Class Component 比較不好使用 hooks，

接下來寫的人可以這樣寫就好：

```
const FormBuilder = () => {};
FormBuilder.propTypes = xxx;
```

**Comment by barry800414** [comment]
Thanks @mark86092 for suggestion 
改好嚕

**Comment by barry800414** [comment]
@peteranny 
Stage 1. 基本 render：3/15 
Stage 2. 基礎互動＆表單事件觸發：3/29
Stage 3. 表單驗證：4/12
Stage 4. 體驗優化：4/26

**Comment by barry800414** [comment]
有個地方要優化，之前 spec 沒有寫清楚
<img width="348" alt="截圖 2020-03-26 下午7 09 20" src="https://user-images.githubusercontent.com/3805975/77640515-790e1e00-6f95-11ea-8910-3e037d0c6796.png">
